# Example of output usage
name: LHCI-output-webhook
on: 
  push:
   branches:
    - main
    
env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  SLACK_USERNAME: Lighthouse Man
  SLACK_ICON_EMOJI: ":up:"

jobs:
  output-webhook:
    name: Slack-Notification
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls:
            https://example.com/
          uploadArtifacts: true
          temporaryPublicStorage: true]
      
      - name: Install jq
        run: sudo apt-get install jq -y  # jqをインストールする

      # JSONファイルの中から"summary"の値を抜き出して出力
      - name: Extract summary from JSON
        run: |
          summary=$(cat /home/runner/work/LighthouseTest/LighthouseTest/.lighthouseci/manifest.json | jq -r '.summary')  # "summary"の値を抜き出す
          echo "::set-output name=summary::$summary"  # 抜き出した値を出力変数にセット

      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_TITLE: Lighthouse ok
          SLACK_COLOR: good
          SLACK_MESSAGE: '{ "links": ${{steps.LHCIAction.outputs.links}}, "manifest": ${{ steps.extract-summary.outputs.summary }} }'
      
      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2.2.0
        if: failure()
        env:
          SLACK_TITLE: Kintai Deploy Failed(master)
          SLACK_COLOR: danger
