# Example of output usage
name: LHCI-output-webhook
on: 
  push:
   branches:
    - main
env:
  SLACK_WEBHOOK: https://hooks.slack.com/services/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
  SLACK_USERNAME: Lighthouse Man
  SLACK_ICON_EMOJI: ":up:"
jobs:
  output-webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notification on Start
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_TITLE: Lighthouse Start
          SLACK_COLOR: "#333333"

      - uses: actions/checkout@v3
      - name: Use output for sending data to API.
        id: LHCIAction
        uses: ./
        with:
          urls: |
            https://treo.sh/

      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_TITLE: Kintai Deploy Finished(master)
          SLACK_COLOR: good
          SLACK_MESSAGE: '{ "links": ${{steps.LHCIAction.outputs.links}}, "manifest": ${{steps.LHCIAction.outputs.manifest}} }'
      
      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2.2.0
        if: failure()
        env:
          SLACK_TITLE: Kintai Deploy Failed(master)
          SLACK_COLOR: danger
          