# Example of output usage
name: LHCI-output-webhook
on: 
  push:
   branches:
    - main
    
env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  SLACK_USERNAME: Lighthouse Man
  SLACK_ICON_EMOJI: ":up:"

jobs:
  output-webhook:
    name: Slack-Notification
    runs-on: ubuntu-latest
    container:
      image: node:10.16-browsers
    steps:

      - uses: actions/checkout@v3

      - run:
          name: Install lighthouse
          command: |
            sudo npm install -g lighthouse
      - run:
          name: Check lighthouse
          command: |
            lighthouse --version
      - run:
          name: Run lighthouse
          command: |
            lighthouse https://example.com/ --output html --output json --output-path ./tomopict.json

      - store_artifacts:
          path: '.'

      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_TITLE: Lighthouse ok
          SLACK_COLOR: good
          SLACK_MESSAGE: '{ "links": ${{steps.LHCIAction.outputs.links}}, "manifest": ${{steps.LHCIAction.outputs.manifest}} }'
      
      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@v2.2.0
        if: failure()
        env:
          SLACK_TITLE: Kintai Deploy Failed(master)
          SLACK_COLOR: danger
